#!/bin/sh

# copy index.html if html directory does not exists

if [ ! -d /web/html ]; then
  mkdir /web/html
fi
cp -rp /etc/apache2/html/* /web/html
chown -R apache.www-data /web/html

# Create vsftpd stuff

#Remove all ftp users
grep '/ftp/' /etc/passwd | cut -d':' -f1 | xargs -n 1 deluser

#Create users
#USERS='name1|password1|[folder1][|uid1] name2|password2|[folder2][|uid2]'
#may be:
# user|password foo|bar|/home/foo
#OR
# user|password|/home/user/dir|10000
#OR
# user|password||10000

#Default user 'ftp' with password 'alpineftp'

if [ -z "$USERS" ]; then
  USERS="ftp|alpineftp"
fi

for i in $USERS ; do
    NAME=$(echo $i | cut -d'|' -f1)
    PASS=$(echo $i | cut -d'|' -f2)
  FOLDER=$(echo $i | cut -d'|' -f3)
     UID=$(echo $i | cut -d'|' -f4)

  # Home folder on /web/html Other posibility is to use syslinks, but on volumes with docker doesnt work fine
  if [ -z "$FOLDER" ]; then
    FOLDER="/web/html/ftp/$NAME"
  fi

  if [ ! -z "$UID" ]; then
    UID_OPT="-u $UID"
  fi

  mkdir -p $FOLDER
  echo -e "$PASS\n$PASS" | adduser --home $FOLDER --shell /sbin/nologin $UID_OPT $NAME
  chown $NAME:$NAME $FOLDER

  # APACHE STUFF
  addgroup $NAME www-data
  addgroup $NAME apache

  unset NAME PASS FOLDER UID
done
